### ISSUE TITLE
Plus signs in the toc's link texts (e.g: in "C++") are overzealously converted to whitespaces

### ISSUE THREAD

**Issue by shlomif** [ekalinin/github-markdown-toc#100]
Hi!

Thanks for all your work on this repository. As can be seen in [this branch](https://github.com/shlomif/Freenode-programming-channel-FAQ/tree/github-markdown-toc--converting-plus-signs-in-headings--to-spaces), `C++` in the link text is being converted to `C\x20\x20`. (The repository makes use of some python3 and GNU make glue - I hope they are acceptable for the demonstration).

I also have written a [patch](https://github.com/shlomif/Freenode-programming-channel-FAQ/blob/c257679290c495e9e9f9c9907215339052a74b60/symptomatic-fix.patch) for github-markdown-toc with a symptomatic fix (which may break other functionality).

**Comment by shlomif** [comment]
Note that I have written a better fix for this issue here: https://github.com/shlomif/github-markdown-toc/tree/shlomif-issue100-better-fix . I didn't write an automated test for it, and I used perl, but it seems to work. Perhaps awk can be used instead of perl in this case.

**Comment by shlomif** [comment]
An update - the branch has now added a regression test and i converted the perl filter to awk code (i dislike awk, but it may be more portable per this repo's policy). Thanks!

**Comment by ekalinin** [comment]
Hey!

Could you, please, create a PR?

**Comment by shlomif** [comment]
> Hey!
> 
> Could you, please, create a PR?

Hi! I can try, but the tests on `upstream/master` branch (`make test`) are currently failing. They should be fixed first. @ekalinin

**Comment by ekalinin** [comment]
> > Hey!
> > Could you, please, create a PR?
> 
> Hi! I can try, but the tests on `upstream/master` branch (`make test`) are currently failing. They should be fixed first. @ekalinin

Fixed.

**Comment by shlomif** [comment]
> > > Hey!
> > > Could you, please, create a PR?
> > 
> > 
> > Hi! I can try, but the tests on `upstream/master` branch (`make test`) are currently failing. They should be fixed first. @ekalinin
> 
> Fixed.

Thanks! See: https://github.com/ekalinin/github-markdown-toc/pull/104 .

**Comment by ekalinin** [comment]
> > > > Hey!
> > > > Could you, please, create a PR?
> > > 
> > > 
> > > Hi! I can try, but the tests on `upstream/master` branch (`make test`) are currently failing. They should be fixed first. @ekalinin
> > 
> > 
> > Fixed.
> 
> Thanks! See: #104 .

Great! Thanks!
