### ISSUE TITLE
[ BUG ] <Replace with bug title>

### ISSUE THREAD

**Issue by paul-hammant** [ekalinin/github-markdown-toc#105]
See:

```
$ gh-md-toc --insert README.md 
gh-md-toc: error: unknown long flag '--insert', try --help
```

The help confirms that.

**Comment by ekalinin** [comment]
Hey @paul-hammant !

Thanks for the report.

As far as i can see:

- https://formulae.brew.sh/formula/github-markdown-toc

This formula relates to another project (gh-md-toc written in go):

- https://github.com/ekalinin/github-markdown-toc.go

So I opened the same issue in that project:

- https://github.com/ekalinin/github-markdown-toc.go/issues/26

And this one will be closed.

**Comment by paul-hammant** [comment]
From the README of ekalinin/github-markdown-toc : 

```
brew install github-markdown-toc
```

That installs a YOUR ruby version of THEIR Go version????????

**Comment by ekalinin** [comment]
> From the README of ekalinin/github-markdown-toc :
> 
> ```
> brew install github-markdown-toc
> ```
> 
> That installs a YOUR ruby version of THEIR Go version????????

Agreed. It's a bit confusing. Removed from README docs related to homebrew.
