### ISSUE TITLE
[Feature] NPM Package

### ISSUE THREAD

**Issue by YashTotale** [ekalinin/github-markdown-toc#106]
**Is your feature request related to a problem? Please describe.**

Not related to a problem, but it would be really helpful if this tool was incorporated as an NPM package.

**Describe the solution you'd like**

This tool is added to the NPM registry and is accessible from Node.

**Describe alternatives you've considered**

No alternatives

**Comment by ekalinin** [comment]
I believe there's a lot of similar tools in the node's ecosystem:
- https://www.npmjs.com/search?q=toc&ranking=popularity
- https://www.google.com/search?q=node+toc
