### ISSUE TITLE
TOC creating from STDIN on Mac OS X without coreutils fails, because BSD version of mktemp command require an argument.

### ISSUE THREAD

**Issue by zer4tul** [ekalinin/github-markdown-toc#11]
TOC creating from STDIN on Mac OS X without GNU coreutils will fail, the error raised out like below:

```bash
$ cat foo.md | gh-md-toc -
gh-md-toc: line 144: $gh_tmp_md: ambiguous redirect
```

It fails because the mktemp command shipped with Mac OS X comes from FreeBSD, witch has different behaviour from the GNU coreutils one.

```bash
$ mktemp
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
```

I've send a pull request to fix this.

**Comment by ekalinin** [comment]
Fixed in #12.
