### ISSUE TITLE
[Question] release

### ISSUE THREAD

**Issue by DanielRamp** [ekalinin/github-markdown-toc#124]
When will you release a new version _(probably 0.7.1 or 0.8.0)_ with the current state of master.

I ask because currently in the docker image `evkalinin/gh-md-toc:0.7.0` the feature `--hide-footer` (flag) is missing and throwing following grep error:
```
$ /app/gh-md-toc --insert --hide-footer README.md

grep: unrecognized option '--hide-footer'
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
You don't have <!--ts--> or <!--te--> in your file...exiting
```

Maybe also consider pushing to `:latest` so we can just specify the image and it always uses the latest version.

**Comment by ekalinin** [comment]
Hey,

Done:
- https://github.com/ekalinin/github-markdown-toc/releases/tag/0.8.0
