### ISSUE TITLE
[SKIP headers before ts -- te]

### ISSUE THREAD

**Issue by firebirdberlin** [ekalinin/github-markdown-toc#125]
When I am creating a TC it always creates an entry of the topmost headlines which are supposed to be above the TOC. I have to remove these entries manually and fix the indentation. 

When using the markers  and  the tool should be able to skip headers above the TOC. 

Example of the current behaviour:
```
M Y T O O L
=========

Table of contents
=============
<!--ts-->
* [M Y T O O L](#m-y-t-o-o-l)
* [Table of contents](#table-of-contents)
* [First](#first)
<!--te-->
```

Desired behaviour:
```
M Y T O O L
=========

Table of contents
=============
<!--ts-->
* [First](#first)
<!--te-->
```

If there is already a way to achieve this please advice :)
Thanks!

**Comment by rdmarsh** [comment]
I would love this behaviour as well. All the examples don't behave like this and I don't know why mine does.

**Comment by Captn138** [comment]
+1 tested the PR and works
