### ISSUE TITLE
[ BUG ] No Table of Contents output

### ISSUE THREAD

**Issue by davetang** [ekalinin/github-markdown-toc#143]
**Describe the bug**
No table of contents is outputted.

**To Reproduce**

```console
echo -e "# README\nfoo\n\n## Sub\nbar" > test.md
wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc
chmod 755 gh-md-toc
./gh-md-toc test.md
```

Output is:

```
Table of Contents
=================



<!-- Created by https://github.com/ekalinin/github-markdown-toc -->
```

**Expected behavior**

Expect table of contents to be generated.

**Environment (please complete the following information):**

```console
./gh-md-toc --version
```
```
0.8.0

os:     Linux
arch:   x86_64
kernel: 3.10.0-962.3.2.lve1.5.66.el7.x86_64
shell:  GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

curl : curl 7.76.1 (x86_64-conda-linux-gnu) libcurl/7.76.1 OpenSSL/1.1.1u zlib/1.2.13 libssh2/1.9.0 nghttp2/1.43.0
wget : GNU Wget 1.20.1 built on linux-gnu.
grep : grep (GNU grep) 2.20
awk  : GNU Awk 4.0.2
sed  : sed (GNU sed) 4.8
```

**Additional context**

This can be replicated across three different machines (all using some flavour of Linux) on different networks. I ran `strace` on `gh-md-toc` and it shows that it makes some network system calls, even when the input is local. Is this necessary?

**Comment by jkburges** [comment]
I had the same problem. Does https://github.com/ekalinin/github-markdown-toc/pull/144 fix it for you?

**Comment by davetang** [comment]
> I had the same problem. Does #144 fix it for you @davetang ?

That fixed it for me too. Thanks.

However, I'm going to switch to [markdown-toc-bash](https://github.com/Lirt/markdown-toc-bash) (which I have forked). I just need a simple script to create a table of contents from a local Markdown file.
