### ISSUE TITLE
no TOC lines returned under OS X

### ISSUE THREAD

**Issue by stowler** [ekalinin/github-markdown-toc#15]
Hello,

Thanks for such a convenient tool! Works great for me on multiple linux platforms.

Unfortunately in OS X the current version returns no TOC lines, even with input .md files that produce the expected output in linux. Looks like it may be related to argument to `$GH_GREP` in `gh_toc_grab()`.Any ideas?

```
$ grep --version
grep (BSD grep) 2.5.1-FreeBSD

$ uname -a
Darwin macbookone.local 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64

$ ./gh-md-toc ~/src.mywork.gitRepos/stowlerGeneralComputing/docs/setupBasicScriptingEnvironment.md

Table of Contents
=================



Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc)

$
```

**Comment by ekalinin** [comment]
Hi @stowler 

I have two suggestions for you:

  * try previous version from here:
    * https://github.com/ekalinin/github-markdown-toc/releases/tag/0.4.4
  * try golang-based version of this script:
    * https://github.com/ekalinin/github-markdown-toc.go
    (It hasn't any dependencies (grep, curl, etc) and should work for you.
On the releases page there're pre-compiled binaries. Please, find one for you OS (``darwin``) and try it.)

**Comment by stowler** [comment]
Hi @ekalinin ,

Thanks. I switched over to github-markdown-toc.go.

-ST
