### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by kurt1984** [ekalinin/github-markdown-toc#18]
Hi 

Thanks for making this solution!

I tried both for local and remote, all like below. is there some package I need to install?

I have all the dependency except bats

 ./gh-md-toc https://github.com/ekalinin/nodeenv/wiki/Who-Uses-Nodeenv

Table of Contents
=================

Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc)

**Comment by ekalinin** [comment]
Hi @kurt1984 

What OS do you use?

Here's my try:
```bash
➥ ./gh-md-toc --version
0.4.5
➥ ./gh-md-toc https://github.com/ekalinin/nodeenv/wiki/Who-Uses-Nodeenv

Table of Contents
=================

  * [Who Uses Nodeenv?](#who-uses-nodeenv)
    * [OpenStack](#openstack)
    * [pre-commit.com](#pre-commitcom)

Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc)
```

**Comment by ekalinin** [comment]
```
➥ cat /etc/issue
Ubuntu 15.04 \n \l
➥ uname -r -i
3.19.0-33-generic x86_64
```

**Comment by kurt1984** [comment]
Hi ekalinin, thanks for your response! 

I am using mac OS10.11

$ ./gh-md-toc --version
0.4.5
$ ./gh-md-toc https://github.com/ekalinin/nodeenv/wiki/Who-Uses-Nodeenv

Table of Contents
=================



Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc)


$ cat /etc/issue
cat: /etc/issue: No such file or directory
$ uname -r -i
uname: illegal option -- i
usage: uname [-amnprsv]

**Comment by ekalinin** [comment]
> Hi ekalinin, thanks for your response!

No problem :)

> I am using mac OS10.11

Yeah, gh-md-toc tested on Ubuntu only. If you want it on Mac OS X or Windows you better to use a golang based implementation:
  * [github-markdown-toc.go](https://github.com/ekalinin/github-markdown-toc.go)

It's more solid, reliable and with ability of a parallel processing. And absolutely without dependencies.

**Comment by ekalinin** [comment]
The same problem was in #16 and #15
