### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by hipposareevil** [ekalinin/github-markdown-toc#29]
Howdy, This isn't an issue, but I created a docker image that runs your script internally.
https://hub.docker.com/r/hipposareevil/github-markdown-toc/

I have it working for the cat version of your usage:
> cat README.md | docker run -i hipposareevil/github-markdown-toc
* [foo] (#foo)
.....

**Comment by ekalinin** [comment]
Hey @hipposareevil 

Cool, thanks!

**Comment by vitalets** [comment]
It would be great to mention in readme. Generating toc without download+chmod is awesome.
