### ISSUE TITLE
Needs integration with sublime text (the MarkdownTOC package).

### ISSUE THREAD

**Issue by dreamcat4** [ekalinin/github-markdown-toc#3]
Hi,
In sublime text there is a package called 'MarkdownTOC'. If can get that existing sublime package's python code to call and invoke this program, then it will auto-regenerate refresh the TOC on every save (Ctrl+S) in Sublime Text.

And that would be awesome.

Because currently MarkdownTOC does the hooks thing well. But not generate TOC correctly (which is very bad output actually). Need the best of both worlds.

**Comment by dreamcat4** [comment]
Where to find Sublime MarkdownTOC:

https://packagecontrol.io/packages/MarkdownTOC

**Comment by dreamcat4** [comment]
Nevermind - this tool can't work on local file (as it parses generated HTML from last push). So it's not suitable for use in sublime.

**Comment by ekalinin** [comment]
btw, just added ability to work with local files. #4
