### ISSUE TITLE
Is there a need for a build step?

### ISSUE THREAD

**Issue by guettli** [ekalinin/github-markdown-toc#32]
Does this project solve the basic problem:

Some kind of build step is needed to create the TOC.

I use this [README](https://github.com/guettli/programming-guidelines) to have a small wiki with version control.

I like editing the page via the github text editor (without local checkout and commit+push)

Can your project create a TOC without a build step?

**Comment by ekalinin** [comment]
Hey,

What do you mean by `build step`?
You just need to run `gh-md-toc` script on your README file.

Please, check the `usage` section in the README:
  * https://github.com/ekalinin/github-markdown-toc#usage

**Comment by guettli** [comment]
@ekalinin  with "build step" I mean if it is needed to call some kind of script (like gh-md-toc).

Thank you for answering this question.
