### ISSUE TITLE
Wrong links if the title has `.` character

### ISSUE THREAD

**Issue by hzy001** [ekalinin/github-markdown-toc#34]
If the title has `.` character, the link returned from the API(https://api.github.com/markdown/raw) will miss the `.` character.
For example,
```
# a.b
```
The related content of the link will be:
```
href="#ab
```

However, the right content should be:
```
href="#a.b
```

**Comment by WhowantsToknow** [comment]
I don't think this is an issue. I've just tested this and it seems the github version of markdown also removes '.' characters when it generates the anchor name. So the link works correctly.

**Comment by ekalinin** [comment]
Not an issue.
