### ISSUE TITLE
read from STDIN or file argument

### ISSUE THREAD

**Issue by logicminds** [ekalinin/github-markdown-toc#4]
Awesome utility.  It would be nice to be able to have this read from STDIN or from a --file attribute.

**Comment by ekalinin** [comment]
Thanks for idea. Seems, it make sense.

**Comment by shrayasr** [comment]
:+1: from me.

If we consider to implement this, multiple files _might_ be a definite requirement like multiple URLs. Does it makes sense for a new flag to be introduced to indicate the source? 

Eg: `--urls` followed by a list of urls and `--files` followed by a list of files.

**Comment by logicminds** [comment]
I would just read the arguments given on the command line and write a function to determine if its a url or file path, then process each.

**Comment by shrayasr** [comment]
Which means that one can process a combination of both URLs and File Paths. :cool:

**Comment by logicminds** [comment]
Personally, I think processing one file at a time would be easier since the output goes to stdout. I am not sure when I would process multiple files at once because the output would be hard to distinguish between each file.

**Comment by shrayasr** [comment]
Agree. I too see more value in doing this one by one than all together. I just pipe it to `pbcopy` and voila, i'm good to go.

But since the tool already supports multiple URL conversion, I brought this up. Not a good idea to break compatibility.

**Comment by shrayasr** [comment]
Took some time out since last night to understand the core logic of how this works. It generates the TOC based on the HTML and not on the markdown. Making it work with local files would mean quite a lot of change because of this.

Please correct me if I'm wrong @ekalinin

**Comment by ekalinin** [comment]
Guys,

Thanks for discussion.
Just added an ability to proccess markdown files (not only html).
Seems, worked. Check out new [README](https://github.com/ekalinin/github-markdown-toc/blob/master/README.md)

**Comment by shrayasr** [comment]
Just noticed how you did it (https://github.com/ekalinin/github-markdown-toc/blob/master/gh-md-toc#L42-L53). That's pretty darned epic. Didn't know GH had an api to convert `.md` to `.html` 

:+1: :smile:

**Comment by ekalinin** [comment]
Thank you :)
