### ISSUE TITLE
Letters with diacritical signs get "messed up"

### ISSUE THREAD

**Issue by mpolakovic** [ekalinin/github-markdown-toc#6]
Hi. I just wanted to let You know that while this works perfectly for English-only characters, some letters with accents and other diacritical signs get "messed up" in the process.

For example, `ň` goes to `%C5%88`, and `í` goes to `%C3%AD`.

I guess the links still work, but it's ugly, and modern browsers can handle these special accentuated letters without a problem.

I suspect this has to do with character encoding, but I am not sure whether this is intentional, or, if not, how to fix this. Thus this issue.

Thank You for Your time and effort

**Comment by ekalinin** [comment]
Hi @mpolakovic!
Thanks for report.

Yes, it seems that there can be a little better.

**Comment by ekalinin** [comment]
Seems fixed in #10
