### ISSUE TITLE
# comments in indent block triggers TOC entry

### ISSUE THREAD

**Issue by pinggit** [ekalinin/github-markdown-toc#63]
```
here is an example:

    root@myserver:~# cat /etc/redis/redis.conf | grep keep
    # TCP keepalive.
    tcp-keepalive 0

```

the above markdown snippet triggers an TOC entry:

```
* [TCP keepalive.](#tcp-keepalive)
```

which is wrong. the TOC should not generated based on the indent block.

**Comment by ekalinin** [comment]
Why not?

https://guides.github.com/features/mastering-markdown/#examples

**Comment by pinggit** [comment]
hi, because indented block should be treated as code block, right?
so if I have a `#` in code block, it should be be treated as a markdown header.
what I noticed is gh-md-toc still treat every occurrence of # as a header, even if it is in code block.
hope this clarified what I meant. I believe this is a bug...

**Comment by pinggit** [comment]
why is this closed?
nothing in code block should be treated as markdown header, correct?
