### ISSUE TITLE
gh-md-toc executed very slow

### ISSUE THREAD

**Issue by jackywu** [ekalinin/github-markdown-toc#7]
$ git clone git@github.com:ekalinin/github-markdown-toc.git
$ cd github-markdown-toc.git
$ ./gh-md-toc README.md > a.md

this command returned after least one minute on Mac OSX 10.10.3 .

**Comment by ekalinin** [comment]
Hi @jackywu ,

Thanks for report.

The speed of this command corresponds to your internet connection speed.
(during this command file is sent to the github)

Here's my results:
```bash
➥ time ./gh-md-toc README.md > a.md

real	0m0.923s
user	0m0.014s
sys	    0m0.018s
```
