### ISSUE TITLE
Sometimes not working

### ISSUE THREAD

**Issue by sant527** [ekalinin/github-markdown-toc#74]
I have  a README.md 

I wanted to create TOC

```
wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc
chmod a+x gh-md-toc
cat README.md | ./gh-md-toc -
```

Sometimes it shows the contents, but sometimes it return blank. I cant understand why sometimes it works and sometimes not

**Comment by ekalinin** [comment]
Hey @sant527 

You're exceeding GitHub API Limit.
Please, take a look here:

- https://github.com/ekalinin/github-markdown-toc#github-token

**Comment by sant527** [comment]
I found that my file size is more than 400kb. The program it didnt shown any messages. When i looked at the source code then i found that.

User limit is  `60 requests per hour.` and with OAuth is `5000 requests per hour`

Thank you

**Comment by sant527** [comment]
Also i am trying to create a personal access token to use this app.

Which scopes i have to accept or tick to access this api
