### ISSUE TITLE
Error: unsupported protocol scheme "c"

### ISSUE THREAD

**Issue by savchenko** [ekalinin/github-markdown-toc#87]
Running on the local source of [stoptracking/windows10/blob/Virt/README.md](https://github.com/stoptracking/windows10/blob/Virt/README.md)

```
.\gh-md-toc.exe --debug C:\Users\xxx\xxx\xxx\xxx\xxx\README.md

Table of Contents
2020/05/11 14:51:41 Convert2HTML: start.
=================
2020/05/11 14:51:41 IsRemoteFile: true

2020/05/11 14:51:41 Convert2HTML: remote file. content-type:
2020/05/11 14:51:41 Convert2HTML: done.
2020/05/11 14:51:41 Get c:\Users\xxx\xxx\xxx\xxx\xxx\README.md: unsupported protocol scheme "c"
```

Am I doing something wrong here? No idea why file type is identified as "remote".

**Comment by ekalinin** [comment]
It looks like it's an issue for go-project:
- https://github.com/ekalinin/github-markdown-toc.go

Please, add a new issue in go-project.
