### ISSUE TITLE
Automated markdown TOC generation with Github Actions

### ISSUE THREAD

**Issue by banzo** [ekalinin/github-markdown-toc#93]
Would it be possible to make this tool available trough [GitHub Actions](https://github.com/features/actions)? This way when someone pushes markdown files, the action would generate the TOC and commit back the updated version of the markdown files.

Note: Maybe this project could be used to commit the updated markdown https://github.com/stefanzweifel/git-auto-commit-action

**Comment by sensuikan1973** [comment]
This is easy, and actually I do.

```.github/workflows/sample_update_toc.yaml
on:
  push:
    branches: [main]
    paths: ['foo.md']

jobs:
  update_toc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o gh-md-toc
          chmod a+x gh-md-toc
          ./gh-md-toc --insert --no-backup foo.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update markdown TOC
```


my example is https://github.com/sensuikan1973/othello-complete-analysis/blob/main/.github/workflows/update_toc.yaml.

**Comment by ekalinin** [comment]
Thanks for the example, @sensuikan1973 !
Do you mind if I add it to the documentation?

**Comment by sensuikan1973** [comment]
sure👍
