### ISSUE TITLE
`don't want to install any additional software.`?

### ISSUE THREAD

**Issue by icy** [ekalinin/github-markdown-toc#94]
> gh-md-toc — is for you if you want to generate TOC for README.md or GitHub's wiki page and don't want to install any additional software.

but in the #installation section of the same README it mentions  something else https://github.com/ekalinin/github-markdown-toc#installation

Am I missing something?

**Comment by ekalinin** [comment]
It's just an installation if the tool itself. It's a script, you can just copy-paste it into your system.

The main point is you don't need to install any extra soft (python, ruby, lua, or any other library).

**Comment by icy** [comment]
Thanks for your feedback. `additional software` is a relative term imho, it depends on the target system. In the dependency section https://github.com/ekalinin/github-markdown-toc#dependency it mentions `gawk` is not supported. I only have `gawk` on my system. Is that possible to use the tool without issue?

Thanks again

**Comment by ekalinin** [comment]
>  I only have gawk on my system. Is that possible to use the tool without issue?

It looks like a typo. I'm using it with with gawk at the moment:

```
➜ ./gh-md-toc ./README.md md

   * [gh-md-toc](./README.md#gh-md-toc)
   * [Table of contents](./README.md#table-of-contents)
   * [Installation](./README.md#installation)
   * [Usage](./README.md#usage)
      * [STDIN](./README.md#stdin)
      * [Local files](./README.md#local-files)
      * [Remote files](./README.md#remote-files)
      * [Multiple files](./README.md#multiple-files)
      * [Combo](./README.md#combo)
      * [Auto insert and update TOC](./README.md#auto-insert-and-update-toc)
      * [GitHub token](./README.md#github-token)
   * [Tests](./README.md#tests)
   * [Dependency](./README.md#dependency)
   * [Docker](./README.md#docker)

Created by [gh-md-toc](https://github.com/ekalinin/github-markdown-toc)

➜ awk -V | head -n1
GNU Awk 4.1.4, API: 1.1 (GNU MPFR 4.0.1, GNU MP 6.1.2)

➜ ls -l /usr/bin/awk         
lrwxrwxrwx 1 root root 21 сен  6  2018 /usr/bin/awk -> /etc/alternatives/awk

➜ ls -l /etc/alternatives/awk
lrwxrwxrwx 1 root root 13 сен  7  2018 /etc/alternatives/awk -> /usr/bin/gawk
```

**Comment by ekalinin** [comment]
Fixed in 488f310064b16c1eb9c17862cc5844189ee65955

**Comment by icy** [comment]
thx a lot @ekalinin . It won't confuse me anymore :P

**Comment by ekalinin** [comment]
Thank you too, @icy for noticing this.
